### ISSUE TITLE
Close ZeebeClient instances automatically

### ISSUE THREAD

**Issue by pihme** [camunda-community-hub/eze#61]
The extension could automatically close instances of ZeebeClient after a test.

Otherwise, you might be greeted with an exception like this:
```
Nov 15, 2021 8:22:48 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=640, target=0.0.0.0:26500} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:625)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:264)
	at io.camunda.zeebe.client.impl.ZeebeClientImpl.buildChannel(ZeebeClientImpl.java:130)
	at io.camunda.zeebe.client.impl.ZeebeClientImpl.<init>(ZeebeClientImpl.java:80)
	at io.camunda.zeebe.client.impl.ZeebeClientBuilderImpl.build(ZeebeClientBuilderImpl.java:282)
	at org.camunda.community.eze.ZeebeEngineImpl.createClient(ZeebeEngineImpl.kt:38)
	at EzeExtension$injectFields$2.invoke(EzeExtension.kt:42)
	at EzeExtension$injectFields$2.invoke(EzeExtension.kt:42)
	at EzeExtension.injectFields(EzeExtension.kt:66)
```

**Comment by Zelldon** [comment]
Will do it soon. I have observed this as well
